name: CI

on:
  push:
  pull_request:

jobs:
  test-linux:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Run tests (pytest)
        run: |
          nix develop --command python -m pytest -q
